resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s        
    instances:
      product: 
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 2s
    instances:
      product:
        base-config: default

spring:
  cloud:
    gateway:
      routes:
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/api/product/**
          #filters:
            #- name: Customizable
              #args:
                #message: Mensaje personalizado
                #cookieName: usuario
                #cookieValue: fcuadros
            #- name: CircuitBreaker
              #args:
                #name: product
                #statusCodes: 500, 404
                #fallbackUri: forward:/api/client/detail/9/count/1
        - id: service-client
          uri: lb://service-client
          predicates:
            - Path=/api/client/**
          filters:
            - AddRequestHeader=token-request, 123456
            - AddResponseHeader=token-response, 78956
            - AddRequestParameter=name, fcuadros